name = "rootbotics"
description = "Rootbotics automated faction assistant."
version = "0.2.1"

authors = ["Dylan E."]
maintainers = ["Dylan E. <76961140+KvanQuilst@users.noreply.github.com>"]
maintainers-logins = ["kvanquilst"]

executables = ["rootbotics"]
